language: ruby

rvm:
  - 2.6
  - 2.7
  - 3.0

gemfile:
  - gemfiles/rspec_3.9_ar_6.0_dc_2.0.gemfile
  - gemfiles/rspec_3.6_ar_5.2.gemfile
  - gemfiles/rspec_3.10_ar_5.2.gemfile
  - gemfiles/rspec_3.9_ar_6.1_dc_2.0.gemfile

matrix:
  exclude:
    - rvm: 3.0
      gemfile: gemfiles/rspec_3.6_ar_5.2.gemfile
    - rvm: 3.0
      gemfile: gemfiles/rspec_3.10_ar_5.2.gemfile

bundler_args: --without development
