name: Test Once-ler
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [3.2, 3.3, 3.4]
        lockfile:
          - Gemfile.activerecord-7.1.lock
          - Gemfile.activerecord-7.2.lock
          - Gemfile.lock
    env:
      BUNDLE_LOCKFILE: ${{ matrix.lockfile }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '${{ matrix.ruby }}'
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake
