name: Test Once-ler
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.7, 3.0, 3.1, 3.2]
        lockfile:
          - Gemfile.activerecord-6.0.lock
          - Gemfile.activerecord-6.1.lock
          - Gemfile.activerecord-7.0.lock
          - Gemfile.lock
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '${{ matrix.ruby }}'
          rubygems: latest
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake
        env: 
          BUNDLE_LOCKFILE: ${{ matrix.lockfile }}

